### ISSUE TITLE
Lando config syntax

### ISSUE THREAD

**Issue by marklabrecque-ab** [sitecrafting/lando-node-cypress#1]
Great job on this repo! Any chance you could paste in your .lando.yml config into the README for others to use? Also your link to the Node custom service appears to be broken.

Thanks so much for providing this stuff!

**Comment by acobster** [comment]
@marklabrecque-ab added! This is a simplified example and I don't have time to test it. Let me know if you need to tweak to get it working. Would very much appreciate a PR if so!

Thanks :)

**Comment by marklabrecque-ab** [comment]
Awesome! Thanks so much! I will definitely send you a PR if anything comes up.

Thanks again!
